#!/usr/bin/env bash
# installing nginx on the web01 server

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html' 
service nginx restart
